FROM cypress/browsers:22.15.0

# Install pnpm
RUN npm install -g pnpm

# Install dependencies
WORKDIR /app

COPY cypress.config.ts .
COPY cypress/ cypress/
COPY package.json .
COPY pnpm-lock.yaml .
COPY tsconfig.json .
COPY tsconfig.node.json .
COPY tsconfig.app.json .

RUN pnpm install && pnpm cypress install

ENTRYPOINT [ "pnpm", "cypress", "run" ]
