FROM cypress/browsers:22.15.0

# Install pnpm
RUN npm install -g pnpm

# Install dependencies
WORKDIR /app

COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm install && pnpm cypress install

COPY tsconfig.json .
COPY tsconfig.node.json .
COPY tsconfig.app.json .
COPY cypress.config.ts .
COPY cypress/ cypress/

ENTRYPOINT [ "pnpm", "cypress", "run" ]
